kumuluzee:
  name: napitnina-service
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/napitninaDS
      connection-url: jdbc:postgresql://napitninaservice:5432/napitnina
      username: postgres
      password: postgres
      max-pool-size: 20